import{a as f,S as p,i as l}from"./assets/vendor-CxFKIfsH.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const m="23963114-6d0d5d874ae460d9125bacd21",g="https://pixabay.com/api/";function y(a){return f.get(g,{params:{key:m,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const d=document.querySelector(".gallery"),n=document.querySelector(".loader-overlay"),h=new p(".gallery a",{captionsData:"alt",captionDelay:250});function v(a){const o=a.map(t=>new Promise(r=>{const e=new Image;e.src=t.webformatURL,e.onload=()=>r(),e.onerror=()=>r()}));return Promise.all(o).then(()=>{const t=a.map(r=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="card-info">
          <div class="info-block"><span class="info-label">Likes</span><span class="info-value">${r.likes}</span></div>
          <div class="info-block"><span class="info-label">Views</span><span class="info-value">${r.views}</span></div>
          <div class="info-block"><span class="info-label">Comments</span><span class="info-value">${r.comments}</span></div>
          <div class="info-block"><span class="info-label">Downloads</span><span class="info-value">${r.downloads}</span></div>
        </div>
      </li>
      `).join("");d.insertAdjacentHTML("beforeend",t),h.refresh()})}function b(){d.innerHTML=""}function L(){n&&n.classList.add("is-active")}function c(){n&&n.classList.remove("is-active")}const u=document.querySelector(".form");u.addEventListener("submit",a=>{a.preventDefault();const o=a.currentTarget.elements.query.value.trim();if(o===""){l.warning({message:"Please enter search query",position:"topRight"});return}b(),L(),y(o).then(t=>{if(t.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. <br> Please try again!",position:"topRight",backgroundColor:"rgba(239, 64, 64, 0.8)",messageColor:"#FFF",iconColor:"#FFFFFF",theme:"dark"});return}return v(t.hits)}).catch(t=>{c(),l.error({message:"Something went wrong!",position:"topRight"}),console.error(t)}).finally(()=>{c(),u.reset()})});
//# sourceMappingURL=index.js.map
