import{a as f,S as u,i}from"./assets/vendor-CxFKIfsH.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const p="23963114-6d0d5d874ae460d9125bacd21",m="https://pixabay.com/api/";function y(t){return f.get(m,{params:{key:p,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data)}const l=document.querySelector(".gallery"),a=document.querySelector(".loader-overlay"),g=new u(".gallery a",{captionsData:"alt",captionDelay:250});function h(t){if(!l)return;const o=t.map(r=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" />
        </a>
        <div class="card-info">
          <div class="info-block"><span class="info-label">Likes</span><span class="info-value">${r.likes}</span></div>
          <div class="info-block"><span class="info-label">Views</span><span class="info-value">${r.views}</span></div>
          <div class="info-block"><span class="info-label">Comments</span><span class="info-value">${r.comments}</span></div>
          <div class="info-block"><span class="info-label">Downloads</span><span class="info-value">${r.downloads}</span></div>
        </div>
      </li>`).join("");l.insertAdjacentHTML("beforeend",o),g.refresh()}function v(){l.innerHTML=""}function b(){a&&a.classList.add("is-active")}function L(){a&&a.classList.remove("is-active")}const d=document.querySelector(".form");d.addEventListener("submit",t=>{t.preventDefault();const o=t.currentTarget.elements.query.value.trim();if(o===""){i.warning({message:"Please enter search query",position:"topRight"});return}v(),b(),y(o).then(r=>{if(r.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. <br> Please try again!",position:"topRight",backgroundColor:"rgba(239, 64, 64, 0.8)",messageColor:"#FFF",iconColor:"#FFFFFF",theme:"dark"});return}h(r.hits)}).catch(r=>{i.error({message:"Something went wrong!",position:"topRight"}),console.error(r)}).finally(()=>{L(),d.reset()})});
//# sourceMappingURL=index.js.map
